name = "DDR2import"
uuid = "60aac331-f4ad-4f7f-9ae1-33a16d2a93d1"
authors = ["René Verbeek"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
